<?php

/**
 * Indicates an exception generated by a ConfigFile operation.
 */
class Vulture_ConfigFileError extends Exception {
  /**
   * Constructor
   * @param string $msg  The error message
   */
  public function __construct($msg) {
    parent::__construct($msg);
  }
}

?>